### ISSUE TITLE
What's the proxy format?

### ISSUE THREAD

**Issue by cChimney** [Itroublve/DiscordJoiner#4]
What's the proxy format? it's saying its joined but it isnt joining.. using rotating residental proxies that work for every other joiner

**Comment by Itroublve** [comment]
HTTP, IP:port:(user:password)

**Comment by cChimney** [comment]
Alr in that case the joiner doesn't work for me.. It says it's joining but it just doesnt. Making them appear online and stuff does work

**Comment by cChimney** [comment]
Also in what format do i put the discord invite maybe thats the problem

**Comment by cChimney** [comment]
nevermind it now works fine for whatever reason

**Comment by Itroublve** [comment]
You change it by Setting a pfp. And it will change all the tokens pfp, same goes for tokens

**Comment by cChimney** [comment]
Alr thanks for the answers tho i do see my tokens getting blocked sadly.. like 2/200 arent blocked

**Comment by Itroublve** [comment]
Well, that's due to your tokens already being flagged by Discord on creation, or your proxies just blacklisted from Discord. Or, of course your token may just be unverified. Which will be fixed in the upcoming releases (If I ever bother to release it..)

**Comment by cChimney** [comment]
It's a rotating proxy aka new proxy each time so can't be blocked and yes they are unverified but they shouldnt get locked after 1 join normally

**Comment by Itroublve** [comment]
Unfortunately, with this method of joining they do, as it's not a complete "bypass"

**Comment by cChimney** [comment]
Alr no problem, lmk on disc or some if u ever gonna release it! thanks m8 cChimney#7815

**Comment by Itroublve** [comment]
@cChimney You may try the newest pre-release, it shall work with unverified tokens now.
