### ISSUE TITLE
It says joined but it doesn't join

### ISSUE THREAD

**Issue by Sh4rK157** [Itroublve/DiscordJoiner#7]
Tried with multiple working tokens with phone and e-mail verified. Tried with and without proxies, but it doesn't join :p

**Comment by Itroublve** [comment]
Uhh, check if you're banned from the API and if your proxies are working. Also, try making new tokens manualy..

**Comment by Sh4rK157** [comment]
Yeah I found the problem, my proxies were not working, isn't there a way to join multiple servers instead of putting one by one? That would be way more effient with a .txt file.
For the name and profile picture changer I think we could use multiple tokens instead of changing one by one.

**Comment by Itroublve** [comment]
I see, I'll look into the multiple invite thingy...

Also, you don't have to change the pfp / name one by one, just put the tokens in the big "Tokens" box on the start and make your changes from Token Settings shall be applied...

**Comment by Itroublve** [comment]
Hey there, so I've updated the joiner to support multiple invites... Right now it requires "," after each invite! The format doesn't matter so just discord.gg/invite,invitees shall work fine!

**Comment by Sh4rK157** [comment]
Thank you very much, this was the fastest reply i've had here on github. You're awesome! And your tool is just amazing!
